replicaCount: 1
env: local
logChannel: stack
repositoryName: CreativeSomething
image:
  repository: creativesomething
  pullPolicy: IfNotPresent
  registry: creativesomething
projectPath: ""
xdebugEnabled: false

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  ports:
    - name: web
      port: 80

ingress:
  enabled: true
  annotations:
    ingress.kubernetes.io/enable-cors: "true"
    kubernetes.io/ingress.class: traefik
  hosts:
    - name: creativesomething
      host: www.creativesomething.test
      paths: ["/"]

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
